const { DataTypes } = require("sequelize");

const _BookingDetailsGdfdiAutovyn = (sequelize) => {
  return sequelize.define(
    "BOOKING_DETAILS_GDFDIAUTOVYN",
    {
      UTD: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      LOC_CD: { type: DataTypes.STRING(50), allowNull: true },
      ORDER_NUM: { type: DataTypes.STRING(50), allowNull: true },
      ORDER_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      CUST_CD: { type: DataTypes.STRING(50), allowNull: true },
      SALUTATION: { type: DataTypes.STRING(20), allowNull: true },
      CUSTOMER_NAME: { type: DataTypes.STRING(200), allowNull: true },
      ADDRESS1: { type: DataTypes.STRING(200), allowNull: true },
      ADDRESS2: { type: DataTypes.STRING(200), allowNull: true },
      ADDRESS3: { type: DataTypes.STRING(200), allowNull: true },
      CITY_DESC: { type: DataTypes.STRING(100), allowNull: true },
      PIN: { type: DataTypes.STRING(20), allowNull: true },
      PIN_DESC: { type: DataTypes.STRING(100), allowNull: true },
      PHONE1: { type: DataTypes.STRING(20), allowNull: true },
      PHONE2: { type: DataTypes.STRING(20), allowNull: true },
      EMAIL_ID: { type: DataTypes.STRING(100), allowNull: true },
      MODEL_DESC: { type: DataTypes.STRING(100), allowNull: true },
       Export_Type: {
      type: DataTypes.TINYINT,
      allowNull: false
    },
      FUEL_DESC: { type: DataTypes.STRING(50), allowNull: true },
      VARIANT_CD: { type: DataTypes.STRING(50), allowNull: true },
      VARIANT_DESC: { type: DataTypes.STRING(100), allowNull: true },
      COLOR_CODE: { type: DataTypes.STRING(50), allowNull: true },
      COLOR_DESC: { type: DataTypes.STRING(50), allowNull: true },
      FINANCER: { type: DataTypes.STRING(200), allowNull: true },
      DSA_NAME: { type: DataTypes.STRING(100), allowNull: true },
      DSA: { type: DataTypes.STRING(50), allowNull: true },
      TEAM_LEAD_NAME: { type: DataTypes.STRING(100), allowNull: true },
      SALES_MAN_CD: { type: DataTypes.STRING(50), allowNull: true },
      EMP_NAME: { type: DataTypes.STRING(100), allowNull: true },
      SALE_TYPE: { type: DataTypes.STRING(50), allowNull: true },
      ORDER_STATUS: { type: DataTypes.STRING(50), allowNull: true },
      BUYER_TYPE: { type: DataTypes.STRING(50), allowNull: true },
      PREFERED_DELIVERY_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      ENQUIRY_TO_ORDER_NO_OF_DAYS: { type: DataTypes.INTEGER, allowNull: true },
      PENDING_DAYS: { type: DataTypes.INTEGER, allowNull: true },
      NO_OF_FOLLOWS: { type: DataTypes.INTEGER, allowNull: true },
      SELLING_PRICE: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      RECEIVED_AMOUNT: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      PROMISED_DELV_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      BALANCE_AMT: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      ENQUIRY_NO: { type: DataTypes.STRING(50), allowNull: true },
      ENQUIRY_SOURCE: { type: DataTypes.STRING(100), allowNull: true },
      ENQUIRY_SUB_SOURCE: { type: DataTypes.STRING(100), allowNull: true },
      SPECIAL_REQUEST: { type: DataTypes.STRING(500), allowNull: true },
      MGA_NET_AMT: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      MGA_SOLD_AMT: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      EW_YES_NO: { type: DataTypes.STRING(5), allowNull: true },
      EW_TYPE: { type: DataTypes.STRING(50), allowNull: true },
      LOYALTY_CARD_YES_NO: { type: DataTypes.STRING(5), allowNull: true },
      LAST_ACTION_DATE: { type: DataTypes.DATE, allowNull: true },
      LAST_ACTION_TAKEN: { type: DataTypes.STRING(200), allowNull: true },
      NEXT_ACTION_PLAN: { type: DataTypes.STRING(200), allowNull: true },
      NEXT_FOLLOWUP_PURPOSE: { type: DataTypes.STRING(200), allowNull: true },
      ACTION_DATE_TIME: { type: DataTypes.DATE, allowNull: true },
      EVALUATOR_NAME: { type: DataTypes.STRING(100), allowNull: true },
      EVALUATOR_MSPIN: { type: DataTypes.STRING(50), allowNull: true },
      OLD_CAR_STATUS: { type: DataTypes.STRING(50), allowNull: true },
      OLD_CAR_REG_NO: { type: DataTypes.STRING(50), allowNull: true },
      OLD_CAR_MODEL: { type: DataTypes.STRING(100), allowNull: true },
      OLD_CAR_SUB_MODEL: { type: DataTypes.STRING(100), allowNull: true },
      EVALUATION_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      BUYING_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      CUSTOMER_EXPECTED_PRICE: {
        type: DataTypes.DECIMAL(18, 2),
        allowNull: true,
      },
      OFFERED_PRICE: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      REFERENCE_PRICE: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      OLD_CAR_CUSTOMER_NAME: { type: DataTypes.STRING(100), allowNull: true },
      TV_NTV_CATEGORY: { type: DataTypes.STRING(50), allowNull: true },
      REFERENCE_TYPE: { type: DataTypes.STRING(50), allowNull: true },
      REFERENCE_BY: { type: DataTypes.STRING(100), allowNull: true },
      REFERENCE_NO: { type: DataTypes.STRING(50), allowNull: true },
      REF_VEHICLE_REGN_NO: { type: DataTypes.STRING(50), allowNull: true },
      REF_MOBILE_NO: { type: DataTypes.STRING(20), allowNull: true },
      STATE: { type: DataTypes.STRING(50), allowNull: true },
      DISTRICT: { type: DataTypes.STRING(50), allowNull: true },
      TEHSIL: { type: DataTypes.STRING(50), allowNull: true },
      VILLAGE: { type: DataTypes.STRING(50), allowNull: true },
      CORPORATE: { type: DataTypes.STRING(50), allowNull: true },
      DELAYED_FLAG: { type: DataTypes.STRING(10), allowNull: true },
      DELAY_REMARKS: { type: DataTypes.STRING(200), allowNull: true },
      DELAY_FLG_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      DELAY_EXPEC_DELV_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      DELAY_DE_FLG_DATE: { type: DataTypes.DATEONLY, allowNull: true },
      ORIGINAL_HSN: { type: DataTypes.STRING(50), allowNull: true },
      AMENDED_HSN: { type: DataTypes.STRING(50), allowNull: true },
      SUBSCRIBER_ID: { type: DataTypes.STRING(50), allowNull: true },
      SUBSCRIBER_NAME: { type: DataTypes.STRING(100), allowNull: true },
      SUBSCRIPTION_ORDER_STATUS: {
        type: DataTypes.STRING(50),
        allowNull: true,
      },
      Created_By: { type: DataTypes.STRING(50), allowNull: true },
    },

   {
      sequelize,
      tableName: "BOOKING_DETAILS_GDFDIAUTOVYN",
      schema: "dbo",
      timestamps: false,
      indexes: [
        {
          name: "PK_BOOKING_DETAILS_GDFDIAUTOVYN",
          unique: true,
          fields: [{ name: "UTD" }],
        },
      ],
    }
  );
};

const Joi = require("joi");

const bookingDetailsSchema = Joi.object({
  LOC_CD: Joi.string().allow(null, ""),
  ORDER_NUM: Joi.string().allow(null, ""),
  ORDER_DATE: Joi.date().allow(null, ""),
  CUST_CD: Joi.string().allow(null, ""),
  SALUTATION: Joi.string().allow(null, ""),
  CUSTOMER_NAME: Joi.string().allow(null, ""),
  ADDRESS1: Joi.string().allow(null, ""),
  ADDRESS2: Joi.string().allow(null, ""),
  ADDRESS3: Joi.string().allow(null, ""),
  CITY_DESC: Joi.string().allow(null, ""),
  PIN: Joi.string().allow(null, ""),
  PIN_DESC: Joi.string().allow(null, ""),
  Export_Type: Joi.number().integer(),
  PHONE1: Joi.string().allow(null, ""),
  PHONE2: Joi.string().allow(null, ""),
  EMAIL_ID: Joi.string().email().allow(null, ""),
  MODEL_DESC: Joi.string().allow(null, ""),
  FUEL_DESC: Joi.string().allow(null, ""),
  VARIANT_CD: Joi.string().allow(null, ""),
  VARIANT_DESC: Joi.string().allow(null, ""),
  COLOR_CODE: Joi.string().allow(null, ""),
  COLOR_DESC: Joi.string().allow(null, ""),
  FINANCER: Joi.string().allow(null, ""),
  DSA_NAME: Joi.string().allow(null, ""),
  DSA: Joi.string().allow(null, ""),
  TEAM_LEAD_NAME: Joi.string().allow(null, ""),
  SALES_MAN_CD: Joi.string().allow(null, ""),
  EMP_NAME: Joi.string().allow(null, ""),
  SALE_TYPE: Joi.string().allow(null, ""),
  ORDER_STATUS: Joi.string().allow(null, ""),
  BUYER_TYPE: Joi.string().allow(null, ""),
  PREFERED_DELIVERY_DATE: Joi.date().allow(null, ""),
  ENQUIRY_TO_ORDER_NO_OF_DAYS: Joi.number().integer().allow(null, ""),
  PENDING_DAYS: Joi.number().integer().allow(null, ""),
  NO_OF_FOLLOWS: Joi.number().integer().allow(null, ""),
  SELLING_PRICE: Joi.number().precision(2).allow(null, ""),
  RECEIVED_AMOUNT: Joi.number().precision(2).allow(null, ""),
  PROMISED_DELV_DATE: Joi.date().allow(null, ""),
  BALANCE_AMT: Joi.number().precision(2).allow(null, ""),
  ENQUIRY_NO: Joi.string().allow(null, ""),
  ENQUIRY_SOURCE: Joi.string().allow(null, ""),
  ENQUIRY_SUB_SOURCE: Joi.string().allow(null, ""),
  SPECIAL_REQUEST: Joi.string().allow(null, ""),
  MGA_NET_AMT: Joi.number().precision(2).allow(null, ""),
  MGA_SOLD_AMT: Joi.number().precision(2).allow(null, ""),
  EW_YES_NO: Joi.string().allow(null, ""),
  EW_TYPE: Joi.string().allow(null, ""),
  LOYALTY_CARD_YES_NO: Joi.string().allow(null, ""),
  LAST_ACTION_DATE: Joi.date().allow(null, ""),
  LAST_ACTION_TAKEN: Joi.string().allow(null, ""),
  NEXT_ACTION_PLAN: Joi.string().allow(null, ""),
  NEXT_FOLLOWUP_PURPOSE: Joi.string().allow(null, ""),
  ACTION_DATE_TIME: Joi.date().allow(null, ""),
  EVALUATOR_NAME: Joi.string().allow(null, ""),
  EVALUATOR_MSPIN: Joi.string().allow(null, ""),
  OLD_CAR_STATUS: Joi.string().allow(null, ""),
  OLD_CAR_REG_NO: Joi.string().allow(null, ""),
  OLD_CAR_MODEL: Joi.string().allow(null, ""),
  OLD_CAR_SUB_MODEL: Joi.string().allow(null, ""),
  EVALUATION_DATE: Joi.date().allow(null, ""),
  BUYING_DATE: Joi.date().allow(null, ""),
  CUSTOMER_EXPECTED_PRICE: Joi.number().precision(2).allow(null, ""),
  OFFERED_PRICE: Joi.number().precision(2).allow(null, ""),
  REFERENCE_PRICE: Joi.number().precision(2).allow(null, ""),
  OLD_CAR_CUSTOMER_NAME: Joi.string().allow(null, ""),
  TV_NTV_CATEGORY: Joi.string().allow(null, ""),
  REFERENCE_TYPE: Joi.string().allow(null, ""),
  REFERENCE_BY: Joi.string().allow(null, ""),
  REFERENCE_NO: Joi.string().allow(null, ""),
  REF_VEHICLE_REGN_NO: Joi.string().allow(null, ""),
  REF_MOBILE_NO: Joi.string().allow(null, ""),
  STATE: Joi.string().allow(null, ""),
  DISTRICT: Joi.string().allow(null, ""),
  TEHSIL: Joi.string().allow(null, ""),
  VILLAGE: Joi.string().allow(null, ""),
  CORPORATE: Joi.string().allow(null, ""),
  DELAYED_FLAG: Joi.string().allow(null, ""),
  DELAY_REMARKS: Joi.string().allow(null, ""),
  DELAY_FLG_DATE: Joi.date().allow(null, ""),
  DELAY_EXPEC_DELV_DATE: Joi.date().allow(null, ""),
  DELAY_DE_FLG_DATE: Joi.date().allow(null, ""),
  ORIGINAL_HSN: Joi.string().allow(null, ""),
  AMENDED_HSN: Joi.string().allow(null, ""),
  SUBSCRIBER_ID: Joi.string().allow(null, ""),
  SUBSCRIBER_NAME: Joi.string().allow(null, ""),
  SUBSCRIPTION_ORDER_STATUS: Joi.string().allow(null, ""),
});

module.exports = { _BookingDetailsGdfdiAutovyn, bookingDetailsSchema };

