const { DataTypes } = require("sequelize");

const _GdFdiTransAutovyn = (sequelize) => {
  return sequelize.define(
    "GD_FDI_TRANS_AUTOVYN",
    {
      UTD: {
  type: DataTypes.INTEGER,
  primaryKey: true,
  autoIncrement: true
},
      PARENT_GROUP: { type: DataTypes.STRING(200), allowNull: true },
      DEALER_MAP_CD: { type: DataTypes.INTEGER, allowNull: true },
      LOC_CD: { type: DataTypes.STRING(200), allowNull: true },
      COMP_FA: { type: DataTypes.STRING(200), allowNull: true },
      MUL_DEALER_CD: { type: DataTypes.STRING(200), allowNull: true },
      OUTLET_CD: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_TYPE: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_DATE: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_ID: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_REF_NUM: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_REF_DATE: { type: DataTypes.STRING(200), allowNull: true },
      TRANS_QTY: { type: DataTypes.FLOAT, allowNull: true },
      TRANS_SEGMENT: { type: DataTypes.STRING(200), allowNull: true },
      VIN: { type: DataTypes.STRING(200), allowNull: true },
      MODEL_CD: { type: DataTypes.STRING(200), allowNull: true },
      VARIANT_CD: { type: DataTypes.STRING(200), allowNull: true },
      ECOLOR_CD: { type: DataTypes.STRING(200), allowNull: true },
      BASIC_PRICE: { type: DataTypes.FLOAT, allowNull: true },
      DISCOUNT: { type: DataTypes.FLOAT, allowNull: true },
      TAXABLE_VALUE: { type: DataTypes.FLOAT, allowNull: true },
      SERVICE_AMOUNT: { type: DataTypes.FLOAT, allowNull: true },
      GST_NO: { type: DataTypes.STRING(200), allowNull: true },
      PLACE_OF_SUPPLY: { type: DataTypes.STRING(200), allowNull: true },
      CUST_NAME: { type: DataTypes.STRING(100), allowNull: true },
      EXECUTIVE: { type: DataTypes.STRING(120), allowNull: true },
      TEAM_HEAD: { type: DataTypes.STRING(100), allowNull: true },
      FINC_NAME: { type: DataTypes.STRING(100), allowNull: true },
      PAYMENT_MODE: { type: DataTypes.STRING(100), allowNull: true },
      DEPOSIT_BANK: { type: DataTypes.STRING(100), allowNull: true },
      PAYMENT_FOR: { type: DataTypes.STRING(100), allowNull: true },
      GE1: { type: DataTypes.STRING(250), allowNull: true },
      GE2: { type: DataTypes.STRING(250), allowNull: true },
      GE3: { type: DataTypes.STRING(250), allowNull: true },
      GE4: { type: DataTypes.STRING(250), allowNull: true },
      GE5: { type: DataTypes.STRING(250), allowNull: true },
      GE6: { type: DataTypes.STRING(250), allowNull: true },
      GE7: { type: DataTypes.STRING(250), allowNull: true },
      GE8: { type: DataTypes.STRING(250), allowNull: true },
      GE9: { type: DataTypes.STRING(250), allowNull: true },
      GE10: { type: DataTypes.STRING(250), allowNull: true },
      GE11: { type: DataTypes.STRING(250), allowNull: true },
      GE12: { type: DataTypes.STRING(250), allowNull: true },
      GE13: { type: DataTypes.STRING(250), allowNull: true },
      GE14: { type: DataTypes.STRING(250), allowNull: true },
      GE15: { type: DataTypes.STRING(250), allowNull: true },
        Export_Type: {
      type: DataTypes.TINYINT,
      allowNull: false
    },
    //   GD_FDI_TRANS_ID: { type: DataTypes.INTEGER, allowNull: false },
      created_date: { type: DataTypes.STRING(200), allowNull: true },
      ENGINE_NUM: { type: DataTypes.STRING(200), allowNull: true },
      CHASSIS_NUM: { type: DataTypes.STRING(200), allowNull: true },
      CUST_ID: { type: DataTypes.STRING(200), allowNull: true },
      HSN_NO: { type: DataTypes.STRING(200), allowNull: true },
      AX_FLAG: { type: DataTypes.STRING(1), allowNull: true },
      AUTOVYN_FLAG: { type: DataTypes.INTEGER, allowNull: true },
    },
    {
      sequelize,
      tableName: "GD_FDI_TRANS_AUTOVYN",
      schema: "dbo",
      timestamps: false,
      indexes: [
        {
          name: "PK_GD_FDI_TRANS_AUTOVYN",
          unique: true,
          fields: [{ name: "UTD" }],
        },
      ],
    }
  );
};

const Joi = require("joi");

const gdFdiTransAutovynSchema = Joi.object({
  PARENT_GROUP: Joi.string().max(200).allow(null, ""),
  DEALER_MAP_CD: Joi.number().allow(null),
  LOC_CD: Joi.string().max(200).allow(null, ""),
  Export_Type: Joi.number().integer(),
  COMP_FA: Joi.string().max(200).allow(null, ""),
  MUL_DEALER_CD: Joi.string().max(200).allow(null, ""),
  OUTLET_CD: Joi.string().max(200).allow(null, ""),
  TRANS_TYPE: Joi.string().max(200).allow(null, ""),
  TRANS_DATE: Joi.string().max(200).allow(null, ""),
  TRANS_ID: Joi.string().max(200).allow(null, ""),
  TRANS_REF_NUM: Joi.string().max(200).allow(null, ""),
  TRANS_REF_DATE: Joi.string().max(200).allow(null, ""),
  TRANS_QTY: Joi.number().allow(null),
  TRANS_SEGMENT: Joi.string().max(200).allow(null, ""),
  VIN: Joi.string().max(200).allow(null, ""),
  MODEL_CD: Joi.string().max(200).allow(null, ""),
  VARIANT_CD: Joi.string().max(200).allow(null, ""),
  ECOLOR_CD: Joi.string().max(200).allow(null, ""),
  BASIC_PRICE: Joi.number().allow(null),
  DISCOUNT: Joi.number().allow(null),
  TAXABLE_VALUE: Joi.number().allow(null),
  SERVICE_AMOUNT: Joi.number().allow(null),
  GST_NO: Joi.string().max(200).allow(null, ""),
  PLACE_OF_SUPPLY: Joi.string().max(200).allow(null, ""),
  CUST_NAME: Joi.string().max(100).allow(null, ""),
  EXECUTIVE: Joi.string().max(120).allow(null, ""),
  TEAM_HEAD: Joi.string().max(100).allow(null, ""),
  FINC_NAME: Joi.string().max(100).allow(null, ""),
  PAYMENT_MODE: Joi.string().max(100).allow(null, ""),
  DEPOSIT_BANK: Joi.string().max(100).allow(null, ""),
  PAYMENT_FOR: Joi.string().max(100).allow(null, ""),
  created_date: Joi.string().max(200).allow(null, ""),
  ENGINE_NUM: Joi.string().max(200).allow(null, ""),
  CHASSIS_NUM: Joi.string().max(200).allow(null, ""),
  CUST_ID: Joi.string().max(200).allow(null, ""),
  HSN_NO: Joi.string().max(200).allow(null, ""),
  AX_FLAG: Joi.string().max(1).allow(null, ""),
  AUTOVYN_FLAG: Joi.number().allow(null),
});

module.exports = { _GdFdiTransAutovyn, gdFdiTransAutovynSchema };
