const Sequelize = require("sequelize");


const _HyundaiWksBillImport  = function (sequelize, DataTypes) {
  return sequelize.define(
        "Hyundai_Workshop_Bill_Import",
        {
    UTD: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    Main_Dealer: { type: DataTypes.STRING(100) },
    Dealer: { type: DataTypes.STRING(100) },
    GST_Invoice_No: { type: DataTypes.STRING(100) },
    GST_Invoice_Date: { type: DataTypes.DATEONLY },
    Payment_Type: { type: DataTypes.STRING(100) },
    Invoiced_To: { type: DataTypes.STRING(100) },
    GSTN_Number: { type: DataTypes.STRING(100) },
    Customer_Type: { type: DataTypes.STRING(100) },
    Type_of_Party: { type: DataTypes.STRING(100) },
    GST_Invoice_Type: { type: DataTypes.STRING(100) },
    Customer_Name: { type:DataTypes.STRING(100) },
    State: { type: DataTypes.STRING(100) },
    Country: { type: DataTypes.STRING(100) },
    Mobile_No: { type: DataTypes.STRING(100) },
    VIN: { type: DataTypes.STRING(100) },
    Vehicle_Reg_No: { type: DataTypes.STRING(100) },
    Model: { type: DataTypes.STRING(100) },
    Work_Type: { type: DataTypes.STRING(100) },
    R_O_No: { type: DataTypes.STRING(100) },
    Service_Advisor: { type: DataTypes.STRING(100) },
    R_O_Close_Date: { type: DataTypes.STRING(100) },
    Total_Amt: { type: DataTypes.STRING(100) },
    Total_Amt_TCS_Tax_Included: { type: DataTypes.STRING(100) },
    Spares_5_Perc: { type: DataTypes.STRING(100) },
    Spares_12_Perc: { type: DataTypes.STRING(100) },
    Spares_18_Perc: { type: DataTypes.STRING(100) },
    Spares_28_Perc: { type: DataTypes.STRING(100) },
    Spares_Bodyshop_5_Perc: { type:DataTypes.STRING(100) },
    Spares_Bodyshop_12_Perc: { type: DataTypes.STRING(100) },
    Spares_Bodyshop_18_Perc: { type: DataTypes.STRING(100) },
    Spares_Bodyshop_28_Perc: { type: DataTypes.STRING(100) },
    Accessories_6_Perc: { type: DataTypes.STRING(100) },
    Accessories_12_Perc: { type: DataTypes.STRING(100) },
    Accessories_18_Perc: { type: DataTypes.STRING(100) },
    Accessories_28_Perc: { type: DataTypes.STRING(100) },
    Number_Plate: { type: DataTypes.STRING(100) },
    Battery_Tyres_Tube: { type: DataTypes.STRING(100) },
    Warranty_Spares: { type: DataTypes.STRING(100) },
    Antirust_Treatment: { type: DataTypes.STRING(100) },
    Consumables_5_Perc: { type: DataTypes.STRING(100) },
    Consumables_18_Perc: { type: DataTypes.STRING(100) },
    Consumables_28_Perc: { type: DataTypes.STRING(100) },
    Oil_Lubricants_5_Perc: { type: DataTypes.STRING(100) },
    Oil_Lubricants_18_Perc: { type: DataTypes.STRING(100) },
    Oil_Lubricants_28_Perc: { type: DataTypes.STRING(100) },
    Paint_Material: { type: DataTypes.STRING(100) },
    Surface_Refinement_Material: { type: DataTypes.STRING(100) },
    Taflon_Coating: { type: DataTypes.STRING(100) },
    Under_Chessis_Coating: { type: DataTypes.STRING(100) },
    Uphoistery_Cleaning: { type: DataTypes.STRING(100) },
    UV_Coating_Material: { type: DataTypes.STRING(100) },
    Lacquer_Coating: { type: DataTypes.STRING(100) },
    Labour_Service: { type: DataTypes.STRING(100) },
    Labour_Bodyshop: { type: DataTypes.STRING(100) },
    CGST_Labor: { type: DataTypes.STRING(100) },
    SGST_Labor: { type: DataTypes.STRING(100) },
    IGST_Labor: { type: DataTypes.STRING(100) },
    One_Perc_Cess_Lbr: { type: DataTypes.STRING(100) },
    Labour_Warranty: { type: DataTypes.STRING(100) },
    Labour_Free_Service: { type: DataTypes.STRING(100) },
    Car_Care: { type: DataTypes.STRING(100) },
    Breakdown_ERS: { type: DataTypes.STRING(100) },
    Emission_Testing: { type: DataTypes.STRING(100) },
    Parking_Estimation: { type: DataTypes.STRING(100) },
    Labour_Towing: { type: DataTypes.STRING(100) },
    CGST_Part_0_Perc: { type: DataTypes.STRING(100) },
    SGST_Part_0_Perc: { type: DataTypes.STRING(100) },
    IGST_Part_0_Perc: { type: DataTypes.STRING(100) },
    CGST_Part_5_Perc: { type: DataTypes.STRING(100) },
    SGST_Part_5_Perc: { type: DataTypes.STRING(100) },
    IGST_Part_5_Perc: { type: DataTypes.STRING(100) },
    CGST_Part_12_Perc: { type: DataTypes.STRING(100) },
    SGST_Part_12_Perc: { type: DataTypes.STRING(100) },
    IGST_Part_12_Perc: { type: DataTypes.STRING(100) },
    CGST_Part_18_Perc: { type: DataTypes.STRING(100) },
    SGST_Part_18_Perc: { type: DataTypes.STRING(100) },
    IGST_Part_18_Perc: { type: DataTypes.STRING(100) },
    CGST_Part_28_Perc: { type: DataTypes.STRING(100) },
    SGST_Part_28_Perc: { type: DataTypes.STRING(100) },
    IGST_Part_28_Perc: { type: DataTypes.STRING(100) },
    CGST_Part: { type: DataTypes.STRING(100) },
    SGST_Part: { type: DataTypes.STRING(100) },
    One_Perc_Cess_Part: { type: DataTypes.STRING(100) },
    Round_Off: { type: DataTypes.STRING(100) },
    TCS_Tax: { type: DataTypes.STRING(100) },
    EInvoice_IRN_No: { type: DataTypes.STRING(100) },
    EInvoice_Acknowledgement_Date: { type: DataTypes.DATEONLY },
    HSN_SAC_Code: { type: DataTypes.STRING(100) },
    Created_By: { type: DataTypes.STRING(255) }, 
   location: { type: DataTypes.STRING(100) },
  },
  {
    sequelize,
    tableName: "Hyundai_Workshop_Bill_Import",
    schema: "dbo",
    timestamps: false,
  }
);
}

const Joi = require("joi");

const Hyundai_Workshop_Bill_Import_Schema = Joi.object({
 Main_Dealer: Joi.string().allow(null, ''),
  Dealer: Joi.string().allow(null, ''),
  GST_Invoice_No: Joi.string().allow(null, ''),
  GST_Invoice_Date: Joi.date().allow(null),
  Payment_Type: Joi.string().allow(null, ''),
  Invoiced_To: Joi.string().allow(null, ''),
  GSTN_Number: Joi.string().allow(null, ''),
  Customer_Type: Joi.string().allow(null, ''),
  Type_of_Party: Joi.string().allow(null, ''),
  GST_Invoice_Type: Joi.string().allow(null, ''),
  Customer_Name: Joi.string().allow(null, ''),
  State: Joi.string().allow(null, ''),
  Country: Joi.string().allow(null, ''),
  Mobile_No: Joi.string().allow(null, ''),
  VIN: Joi.string().allow(null, ''),
  Vehicle_Reg_No: Joi.string().allow(null, ''),
  Model: Joi.string().allow(null, ''),
  Work_Type: Joi.string().allow(null, ''),
  R_O_No: Joi.string().allow(null, ''),
  Service_Advisor: Joi.string().allow(null, ''),
  R_O_Close_Date: Joi.string().allow(null, ''),
  Total_Amt: Joi.string().allow(null, ''),
  Total_Amt_TCS_Tax_Included: Joi.string().allow(null, ''),
  Spares_5_Perc: Joi.string().allow(null, ''),
  Spares_12_Perc: Joi.string().allow(null, ''),
  Spares_18_Perc: Joi.string().allow(null, ''),
  Spares_28_Perc: Joi.string().allow(null, ''),
  Spares_Bodyshop_5_Perc: Joi.string().allow(null, ''),
  Spares_Bodyshop_12_Perc: Joi.string().allow(null, ''),
  Spares_Bodyshop_18_Perc: Joi.string().allow(null, ''),
  Spares_Bodyshop_28_Perc: Joi.string().allow(null, ''),
  Accessories_6_Perc: Joi.string().allow(null, ''),
  Accessories_12_Perc: Joi.string().allow(null, ''),
  Accessories_18_Perc: Joi.string().allow(null, ''),
  Accessories_28_Perc: Joi.string().allow(null, ''),
  Number_Plate: Joi.string().allow(null, ''),
  Battery_Tyres_Tube: Joi.string().allow(null, ''),
  Warranty_Spares: Joi.string().allow(null, ''),
  Antirust_Treatment: Joi.string().allow(null, ''),
  Consumables_5_Perc: Joi.string().allow(null, ''),
  Consumables_18_Perc: Joi.string().allow(null, ''),
  Consumables_28_Perc: Joi.string().allow(null, ''),
  Oil_Lubricants_5_Perc: Joi.string().allow(null, ''),
  Oil_Lubricants_18_Perc: Joi.string().allow(null, ''),
  Oil_Lubricants_28_Perc: Joi.string().allow(null, ''),
  Paint_Material: Joi.string().allow(null, ''),
  Surface_Refinement_Material: Joi.string().allow(null, ''),
  Taflon_Coating: Joi.string().allow(null, ''),
  Under_Chessis_Coating: Joi.string().allow(null, ''),
  Uphoistery_Cleaning: Joi.string().allow(null, ''),
  UV_Coating_Material: Joi.string().allow(null, ''),
  Lacquer_Coating: Joi.string().allow(null, ''),
  Labour_Service: Joi.string().allow(null, ''),
  Labour_Bodyshop: Joi.string().allow(null, ''),
  CGST_Labor: Joi.string().allow(null, ''),
  SGST_Labor: Joi.string().allow(null, ''),
  IGST_Labor: Joi.string().allow(null, ''),
  One_Perc_Cess_Lbr: Joi.string().allow(null, ''),
  Labour_Warranty: Joi.string().allow(null, ''),
  Labour_Free_Service: Joi.string().allow(null, ''),
  Car_Care: Joi.string().allow(null, ''),
  Breakdown_ERS: Joi.string().allow(null, ''),
  Emission_Testing: Joi.string().allow(null, ''),
  Parking_Estimation: Joi.string().allow(null, ''),
  Labour_Towing: Joi.string().allow(null, ''),
  CGST_Part_0_Perc: Joi.string().allow(null, ''),
  SGST_Part_0_Perc: Joi.string().allow(null, ''),
  IGST_Part_0_Perc: Joi.string().allow(null, ''),
  CGST_Part_5_Perc: Joi.string().allow(null, ''),
  SGST_Part_5_Perc: Joi.string().allow(null, ''),
  IGST_Part_5_Perc: Joi.string().allow(null, ''),
  CGST_Part_12_Perc: Joi.string().allow(null, ''),
  SGST_Part_12_Perc: Joi.string().allow(null, ''),
  IGST_Part_12_Perc: Joi.string().allow(null, ''),
  CGST_Part_18_Perc: Joi.string().allow(null, ''),
  SGST_Part_18_Perc: Joi.string().allow(null, ''),
  IGST_Part_18_Perc: Joi.string().allow(null, ''),
  CGST_Part_28_Perc: Joi.string().allow(null, ''),
  SGST_Part_28_Perc: Joi.string().allow(null, ''),
  IGST_Part_28_Perc: Joi.string().allow(null, ''),
  CGST_Part: Joi.string().allow(null, ''),
  SGST_Part: Joi.string().allow(null, ''),
  One_Perc_Cess_Part: Joi.string().allow(null, ''),
  Round_Off: Joi.string().allow(null, ''),
  TCS_Tax: Joi.string().allow(null, ''),
  EInvoice_IRN_No: Joi.string().allow(null, ''),
  EInvoice_Acknowledgement_Date: Joi.date().allow(null),
  HSN_SAC_Code: Joi.string().allow(null, ''),
  Created_By: Joi.string().allow(null, ''),

  location: Joi.string().allow(null, ''),
});


module.exports = {
  _HyundaiWksBillImport,
  Hyundai_Workshop_Bill_Import_Schema,
};